name: Bug report
description: Create a bug report to help us improve WunderGraph
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve WunderGraph! 🙏 Please follow the sections in the template and provide as much information as possible about your problem, e.g. by setting the `wunderctl --debug` option in the WunderCtl Client.
  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior
      value: |
        <!--
        1. Go to '...'
        2. Change '....'
        3. Run '....'
        4. See error
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: WunderGraph information
      description: Your WunderGraph operations, wundergraph.config.ts, wundergraph.operations.ts, wundergraph.server.ts, ...
      value: |
        <!-- Do not include your credentials when sharing your configurations! -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment & setup
      description: In which environment does the problem occur
      value: |
        - OS: <!--[e.g. Mac OS, Windows, Debian, CentOS, ...]-->
        - Go version: <!--[Run `go version` to see your Go version]-->
        - Database: <!--[PostgreSQL, MySQL, MariaDB or SQLite]-->
        - Node.js version: <!--[Run `node -v` to see your Node.js version]-->
    validations:
      required: true
  - type: textarea
    attributes:
      label: WunderCtl Version
      description: Run `wunderctl version` to see your WunderCtl version and paste it between the ´´´
      value: |
        ```

        ```
    validations:
      required: true
