name: "Setup Go"
description: "This action install go and cache modules and build dependencies"
inputs:
  go-version:
    description: 'The go version to install'
    default: '1.18'
    required: false
  working-directory:
    description: 'The working directory of your go module'
    default: '.'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ format('{0}-go-{1}', runner.os, hashFiles(format('{0}/**/go.sum', inputs.working-directory ))) }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
