# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
#    - sudo cp -r /home/runner/go/pkg/mod/github.com/jensneuse/goprisma@v0.0.11/lib/ /home/runner/work/wundergraph/
    # you may remove this if you don't need go generate
    - go generate ../...
builds:
  - binary: wunderctl
    id: linux
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w -s -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=ci main.githubAuthDemoClientID={{.Env.GH_AUTH_DEMO_CLIENT_ID}} main.githubAuthDemoClientSecret={{.Env.GH_AUTH_DEMO_CLIENT_SECRET}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: wundergraph
    name: wundergraph
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_linux_checksums.txt"
