name: engine-release-linux
on:
  push:
    tags: ['v*']
    
env:
  CI: true

jobs:
    goreleaser:
      name: run goreleaser
      runs-on: 'ubuntu-latest'
      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: Install Protoc
          uses: arduino/setup-protoc@v1
          with:
            version: '3.x'

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.18

        - name: go env
          run: go env

        - name: generate go types based on protobuf definitions
          run: make codegen

        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v2
          with:
            version: latest
            workdir: './cmd/wunderctl'
            args: release --rm-dist --config ./../../.github/goreleaser/.goreleaser-linux.yml
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN_GORELEASER }}
            AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
            GH_AUTH_DEMO_CLIENT_ID: ${{ secrets.GH_AUTH_DEMO_CLIENT_ID }}
            GH_AUTH_DEMO_CLIENT_SECRET: ${{ secrets.GH_AUTH_DEMO_CLIENT_SECRET }}
