name: Wunderctl Changesets

on:
  push:
    tags: ['v*']

env:
  CI: true

jobs:
  # Update package versions from changesets.
  version:
    timeout-minutes: 14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          
      - name: Add changeset to release wunderctl ${{ github.ref_name }}
        env: 
          WUNDERCTL_VERSION: ${{ github.ref_name }}
        run: |
          echo -e "---\n'@wundergraph/wunderctl': patch\n---\n\nRelease ${WUNDERCTL_VERSION}" > .changeset/wunderctl-${WUNDERCTL_VERSION}.md

      - run: pnpm boot --ignore-scripts

      - run: pnpm build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
          commit: '[ci] wunderctl release'
          title: '[ci] wunderctl release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
